overview page added
SkyHighConstruction/HD-Project pull request #2
Opened 2023-05-20 15:57 UTC by Hikaaruu

2023-05-20 16:53 UTC, SkyHighConstruction requested changes
Зможеш зробити табличку з повзунком, щоб не виходила за футер?
<img width="1433" alt="image" src="https://github.com/SkyHighConstruction/HD-Project/assets/80775870/1659824c-200a-4cb8-a211-bd8dd4b5f485">

2023-05-20 18:37 UTC, Hikaaruu commented
Це ти як зробив? У мене просто там є скрипт який рахує кількість сторінок і розбиває по 10 елементів на сторінку

2023-05-20 20:24 UTC, SkyHighConstruction commented
> Це ти як зробив? У мене просто там є скрипт який рахує кількість сторінок і розбиває по 10 рядків на сторінку

Тут проблема не в цьому, скрипт працює норм. Таблиця виходить за межі класу main при завеликій ширині

2023-05-20 23:23 UTC, Hikaaruu commented
Наче виправив

2023-05-21 08:45 UTC, SkyHighConstruction approved these changes
👍

2023-05-21 08:45 UTC, merged